version: 0.1
os: linux
files:
  - source: ./www/index.html
    destination: /usr/share/http-endpoint/
  - source: ./.build/codedeploy/site.conf
    destination: /etc/nginx/conf.d/

hooks:
  BeforeInstall:
    - location: .build/codedeploy/install.sh
      timeout: 300
  ApplicationStop:
    - location: .build/codedeploy/stop.sh
      timeout: 30
  ApplicationStart:
    - location: .build/codedeploy/start.sh
timeout: 30